#!/bin/sh
set -e

mkdir -p /proc
mount -t proc proc /proc
mkdir -p /sys
mount -t sysfs proc /sys
mount -t cgroup2 none /sys/fs/cgroup
mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

# Disabling ipv6 networking stack for performance reasons (~1s overhead on startup)
sysctl -q net.ipv6.conf.all.disable_ipv6=1

# 10.0.2.15 is the IP address assigned automatically by QEMU to a VM
# when using -nic user. (see: https://www.qemu.org/docs/master/system/devices/net.html)
ip link set eth0 up
ip addr add 10.0.2.15/24 dev eth0
ip route add default via 10.0.2.2

ip link set lo up
hostname sandbox

if grep -qw "init_recovery=1" /proc/cmdline; then
    # The number of host-tty device depends on the order of arguments passed to QEMU
    # Just in case if we mess things up listing all vport devices in recovery mode
    echo "Serial devices:"
    ls /dev/vport*
    /bin/server --serial /dev/vport0p1 -- "$@"
else
    mkdir -p /mnt
    mount /dev/vda /mnt

    mount -o move /proc /mnt/proc
    mount -o move /sys /mnt/sys
    mount -t devtmpfs devtmpfs /mnt/dev
    mkdir -p /mnt/dev/shm
    mount -t tmpfs tmpfs /mnt/dev/shm

    mkdir -p /mnt/run
    mount -t tmpfs tmpfs /mnt/run

    # Preparing system DNS resolver
    if [ -d /mnt/etc ]; then
        # resolv.conf might be existing and might be a symlink, in which case we need to remove it first
        rm -f /mnt/etc/resolv.conf
        # 10.0.2.3 is a default DNS provided by QEMU user networking (eg. `-netdev user`)
        # QEMU libslirp only uses 1st DNS resolver from host machine.
        # If IPv6 stack is configured on a host machine it probably will have an IPv6 DNS server and it might
        # cause DNS resolution issues. We add second DNS as a fallback.
        echo -e "nameserver 10.0.2.3\nnameserver 8.8.8.8" > /mnt/etc/resolv.conf
    fi

    # From now on we do not care about exit code. We stee need to move on
    set +e

    # The kernel passes everything after "--" on its command line to init as
    # arguments; they are the command to run
    /bin/server --serial /dev/vport0p1 --chroot /mnt -- "$@"

    # Moving system mounts back
    # Filesystems should be unmounted in the opposite order
    umount /mnt/dev
    mount -o move /mnt/sys /sys
    mount -o move /mnt/proc /proc

    umount /mnt
fi
sync
poweroff -f
