[package]
name = "qemu-agent"
version = "0.1.0"
edition = "2024"

[lib]
name = "qemu_agent"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[dependencies]
thiserror = "2"
crossterm = "0.28"
rand = "0.10.1"
tempdir = "0.3.7"
nix = { version = "0.31.3", features = ["term"] }
clap = { version = "4.6.1", features = ["derive"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
signal-hook = "0.3"

[dev-dependencies]
regex = "1.12.4"
