#!/bin/sh
set -e

mkdir -p /proc
mount -t proc proc /proc
mkdir -p /sys
mount -t sysfs proc /sys
mount -t cgroup2 none /sys/fs/cgroup
mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

# Disabling ipv6 networking stack for performance reasons (~1s overhead on startup)
sysctl -q net.ipv6.conf.all.disable_ipv6=1

# 10.0.2.15 is the IP address assigned automatically by QEMU to a VM
# when using -nic user. (see: https://www.qemu.org/docs/master/system/devices/net.html)
ip link set eth0 up
ip addr add 10.0.2.15/24 dev eth0
ip route add default via 10.0.2.2

ip link set lo up
hostname sandbox

if grep -qw "init_recovery" /proc/cmdline; then
    # The number of host-tty device depends on the order of arguments passed to QEMU
    # Just in case if we meess things up listing all vport devices in recovery mode
    echo "Serial devices:"
    ls /dev/vport*
    exec /bin/server --serial /dev/vport0p1 /bin/sh
else
    # The kernel passes everything after "--" on its command line to init
    # as arguments; use them as the starting command if present.
    if [ $# -eq 0 ]; then
        set -- /usr/bin/login -f root
    fi

    mkdir -p /mnt
    mount /dev/vda /mnt

    mkdir -p /mnt/workspace
    mount -t 9p -o trans=virtio qemu /mnt/workspace -oversion=9p2000.L,msize=524288 || 0

    mount -o move /proc /mnt/proc
    mount -o move /sys /mnt/sys
    mount -t devtmpfs devtmpfs /mnt/dev
    mkdir -p /mnt/dev/shm
    mount -t tmpfs tmpfs /mnt/dev/shm

    # From now on we do not care about exit code. We stee need to move on
    set +e
    # This line is very convoluted, so let's break it down:
    #
    # 1. because server will allocate a tty we only can move /dev/pts mount after server is already running.
    #    we can not do it before like with other mount points. Ideally server should does it itself, but it's not
    #    implemented yet.
    # 2. we use /bin/sh to run several commands after server is started an dallocated pty
    # 3. we need to pass entrypoint arguments to chroot ("$@" part), but we can not do it in a straighforward way
    #    unfortunatley. `chroot /mnt "$@"` will not work, because it will break after shell expansion if there
    #    were arguments with spaces and double quotes.
    #
    # The proper way to solve it probably, is to move `mount -o move` part to the server itself
    /usr/bin/env -i TERM=xterm-color /bin/server --serial /dev/vport0p1 -- /bin/sh -c "mount -o move /dev/pts /mnt/dev/pts; /usr/sbin/chroot /mnt \"\$@\"" -- "$@"

    # Moving system mounts back
    # Filesystems should be unmounted in the opposite order
    mount -o move /mnt/dev/pts /dev/pts
    umount /mnt/dev
    mount -o move /mnt/sys /sys
    mount -o move /mnt/proc /proc

    umount /mnt/workspace
    umount /mnt
fi
sync
poweroff -f
