#!/bin/sh
set -e

mkdir -p /proc
mount -t proc proc /proc
mkdir -p /sys
mount -t sysfs proc /sys
mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

# Disabling ipv6 networking stack for performance reasons (~1s overhead on startup)
sysctl -q net.ipv6.conf.all.disable_ipv6=1

# 10.0.2.15 is the IP address assigned automatically by QEMU to a VM
# when using -nic user. (see: https://www.qemu.org/docs/master/system/devices/net.html)
ip link set eth0 up
ip addr add 10.0.2.15/24 dev eth0
ip route add default via 10.0.2.2

ip link set lo up
hostname sandbox

if grep -qw "init_recovery" /proc/cmdline; then
    exec /bin/server --serial /dev/vport2p1 /bin/sh
else
    mkdir -p /mnt
    mount /dev/vda /mnt

    mkdir -p /mnt/workspace
    mount -t 9p -o trans=virtio qemu /mnt/workspace -oversion=9p2000.L,msize=524288 || 0

    mount -o move /proc /mnt/proc
    mount -o move /sys /mnt/sys
    mount -t devtmpfs devtmpfs /mnt/dev
    mount -t devpts devpts /mnt/dev/pts

    # From now on we do not care about exit code. We stee need to move on
    set +e
    /usr/bin/env -i TERM=xterm-color /bin/server --serial /dev/vport2p1 -- /usr/sbin/chroot /mnt /usr/bin/login -f root

    # Moving system mounts back
    # Filesystems should be unmounted in the opposite order
    umount /mnt/dev/pts
    umount /mnt/dev
    mount -o move /mnt/sys /sys
    mount -o move /mnt/proc /proc

    umount /mnt/workspace
    umount /mnt
fi
sync
poweroff -f
